name: XPanel
version: 0.0.1
version_from: lib/XPanel.pm
installdirs:  site
requires:
   CGI::Session:	0
   File::Type:		0
   Digest::MD5:		0
   Test::More:		0
   HTML::Template:	0
   Geo::IP::PurePerl:	0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
